CREATE USER dbmsproject
IDENTIFIED BY pass
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp;

GRANT CONNECT, 
CREATE SESSION, 
CREATE TABLE, 
CREATE SEQUENCE, 
CREATE PROCEDURE,
CREATE TRIGGER, 
UNLIMITED TABLESPACE 
TO dbmsproject;

ALTER USER dbmsproject QUOTA UNLIMITED ON USERS;