SELECT * FROM DOCTOR;
SELECT * FROM PATIENT;
SELECT * FROM PHARMACEUTICAL_COMPANY;
SELECT * FROM PHARMACY;
SELECT * FROM DRUG;
SELECT * FROM PRESCRIPTION;
SELECT * FROM PHARMACY_DRUGS;
SELECT * FROM PHARMACY_CONTRACT;
